packages:
  - packages/*
  - packages/adapters/*
  - packages-next/*
  - example/*
  - website

autoInstallPeers: true

onlyBuiltDependencies:
  - esbuild
  - onnxruntime-node

onlyBuiltDependenciesFile: ""
