/**
 * `@agentick/spec/errors` — v2 typed-error infrastructure.
 *
 * Foundation for ADR 41. This barrel exports:
 *
 *   - `AgentickError` (abstract root + `SerializedAgentickError` wire
 *     shape + `isAgentickError` predicate)
 *   - `registerAgentickError` / `lookupAgentickError` — class registry
 *     keyed by `_tag`
 *   - `serializeAgentickError` / `deserializeAgentickError` — JSON
 *     codec round-trip
 *   - `UnknownAgentickError` — fallback for unregistered tags
 *
 * Concrete error classes (per-domain abstract intermediates +
 * leaf classes) land in subsequent commits and re-export from this
 * barrel. This commit lands the base machinery only — no consumer
 * package's error types have been migrated yet.
 *
 * @see docs/proposals/v2/blueprint/41-error-hierarchy.md
 */

export {
  AgentickError,
  type AgentickErrorOptions,
  type AgentickErrorTag,
  type SerializedAgentickError,
  isAgentickError,
} from "./base.js";

export {
  type ConcreteAgentickErrorClass,
  registerAgentickError,
  lookupAgentickError,
  _clearAgentickErrorRegistry,
  _registeredAgentickErrorTags,
} from "./registry.js";

export { deserializeAgentickError, serializeAgentickError } from "./codec.js";

export { UnknownAgentickError } from "./unknown.js";

export {
  AddressNotFound,
  AskTimeout,
  CommandDeclarationError,
  HandlerError,
  InboxClosed,
  InboxError,
  type InboxErrorChannel,
  InvalidPayload,
  JournalError,
  type JournalErrorChannel,
  LifecycleHandlerError,
  MessageHandlerError,
  type MessageHandlerErrorChannel,
  OffsetOutOfRange,
  ReadFailed,
  RoutingFailed,
  WriteFailed,
} from "./substrate.js";

export {
  AppAlreadyExistsError,
  AppClosedError,
  AppError,
  type AppErrorChannel,
  AppExecutionFailed,
  AppNotFoundError,
  ChannelError,
  ExecutionFailed,
  GatewayBridgeSlotOccupied,
  GatewayClosedError,
  GatewayError,
  type GatewayErrorChannel,
  GatewayLifecycleError,
  GatewayNotStartedError,
  KnobError,
  InvalidMediaSource,
  ModelExecutorBuilderMissingError,
  NoModelForExecutionError,
  SessionBusyError,
  SessionClosedError,
  SessionError,
  type SessionErrorChannel,
  SessionNotFoundError,
  BranchSourceEntryNotFoundError,
  SessionTimelineError,
  SpawnDepthExceededError,
  type StateApplyError,
  type StateApplyErrorChannel,
  TimelineWriteFailed,
} from "./lifecycle.js";

export {
  AlreadyMounted,
  BridgeUnavailable,
  causeMessage,
  clampErrorDetail,
  CompactHandlerFailed,
  CompactStrategyMissing,
  CredentialsBackendUnavailable,
  CredentialsCorrupted,
  CredentialsError,
  type CredentialsErrorChannel,
  CredentialsNotFound,
  CredentialsWriteFailed,
  DataFetchFailed,
  ExecuteError,
  type ExecuteErrorChannel,
  ExecutionError,
  FormatterFailed,
  GroupEmpty,
  GroupTypeMismatch,
  InvalidDispatchInput,
  InvalidElement,
  KnobsError,
  type KnobsErrorChannel,
  LoopCanceledError,
  LoopExecutorError,
  type LoopExecutorErrorChannel,
  MaxIterationsExceeded,
  MaxTicksExceeded,
  TerminalToolNameCollision,
  StructuredOutputIncomplete,
  MultipleStructuredOutputs,
  ElicitError,
  type ElicitErrorChannel,
  ElicitationCancelled,
  ElicitationDeclined,
  ElicitationNotSupported,
  ElicitSchemaTooComplex,
  McpServerAuthRejected,
  McpServerAuthzDenied,
  McpServerClosed,
  McpServerConfigInvalid,
  McpServerConnectionRejected,
  McpServerError,
  type McpServerErrorChannel,
  McpServerNotFound,
  McpServerRateLimited,
  McpServerTransportFailed,
  UrlElicitationRequired,
  type UrlElicitationSpec,
  NormalizationFailed,
  NotMounted,
  PromptAlreadyExists,
  PromptArgumentInvalid,
  PromptArgumentMissing,
  PromptMissingContent,
  PromptNotFound,
  PromptRenderFailed,
  PromptsBackendError,
  PromptsHydrateFailed,
  ProjectionFailed,
  PromptsError,
  type PromptsErrorChannel,
  GateNotFound,
  GatesError,
  type GatesErrorChannel,
  ResourceAliasAmbiguous,
  ResourceAlreadyRegistered,
  ResourceNotFound,
  ResourceResolverFailed,
  ResourcesBackendError,
  ResourcesError,
  type ResourcesErrorChannel,
  isExecuteError,
  MalformedModelOutput,
  ProviderAborted,
  ProviderRejected,
  ProviderTimeout,
  ReconcileError,
  type ReconcileErrorChannel,
  TimelineHydrateFailed,
  RenderFailed,
  SkillAlreadyExists,
  SkillIsolationUnavailable,
  SkillNotFound,
  SkillRunnerUnbound,
  SkillsBackendError,
  SkillsError,
  SkillsHydrateFailed,
  type SkillsErrorChannel,
  StreamFailed,
  TickError,
  TimelineError,
  type TimelineErrorChannel,
  ToolAbortedError,
  ToolAlreadyRegistered,
  ToolCallTimeoutError,
  ToolConfirmationDeniedError,
  ToolConfirmationTimeoutError,
  ToolExecutorError,
  type ToolExecutorErrorChannel,
  ToolHandlerError,
  ToolHandlerMissing,
  ToolNotFoundError,
  ToolPermissionError,
  ToolTaskModeConflictError,
  ToolTimeoutError,
  ToolValidationError,
  UnknownExecutorError,
  UnknownKnob,
  UnstableTree,
  ValidationFailed,
  type ExecutorErrorChannel,
} from "./harnesses.js";

export {
  ChannelPublishError,
  type ChannelPublishErrorChannel,
  ChannelPublisherClosed,
  ChannelSequenceOverflow,
  IngressAuthError,
  type IngressAuthErrorChannel,
  IngressAuthFailed,
  IngressAuthRequired,
  IngressCredentialUnsupported,
  McpClientError,
  type McpClientErrorChannel,
  McpClientNotReadyError,
  McpCredentialsRequiredError,
  McpRemoteTaskNonCompletedError,
  McpTransportError,
  SandboxConnectionError,
  SandboxError,
  type SandboxErrorChannel,
  SandboxEscapeError,
  SandboxExecError,
  SandboxIoError,
  SandboxMountError,
  SandboxPermissionDeniedError,
  SandboxResourceLimitError,
  SandboxUnsupportedError,
  SteerCannotCarryStructuredOutput,
  ResponseValidationError,
  DetachedTaskCannotElicitError,
  TaskHandlerRefRequiredError,
  UnknownTaskError,
  UnknownTaskExecutorError,
  WireExtensionDefinitionError,
} from "./remaining.js";
